name: Auto Import GSheet

on:
  schedule:
    - cron: '0 * * * *' # Jalan tiap jam
  workflow_dispatch: # Tombol manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install gspread oauth2client

      - name: Run Script
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python importlgsg.py
